### ISSUE TITLE
Add WP links or docs links

### ISSUE THREAD

**Issue by serejandmyself** [lovincyrus/cosmonauts-world#34]
https://github.com/lovincyrus/cosmonauts-world/issues/33

I assume this could help people a bit more insight into the projects.

**Comment by lovincyrus** [comment]
Thanks for the suggestion! @serejandmyself 

> I assume this could help people a bit more insight into the projects.

Adding a docs links to the projects would definitely provide more insights. Unfortunately, we don't have the resources to keep track of the docs links atm. The docs subdomain or paths could change from time to time. Unless someone would be willing to fill in all the projects' docs, otherwise i'm all for it 🤜🏼

Also, I have this https://github.com/lovincyrus/cosmonauts-world/issues/57 planned for the roadmap.
