### ISSUE TITLE
Create incentives for early submission

### ISSUE THREAD

**Issue by haymond** [lovincyrus/cosmonauts-world#53]
One of the challenges we have as an open-source project is that teams sometimes come out of the blue, announcing their support for the Cosmos SDK, Tendermint Core, or IBC. 

It would be great if we provided an incentive for them to submit their project on Cosmonauts World first, so we're aware of their existence. This could be a Cosmos T-Shirt or some other type of swag. 

The goal is that over time, we won't need to provide any incentive because simply listing on Cosmonauts World will get enough visibility for new projects. This is more of an open discussion to head in that direction.

**Comment by lovincyrus** [comment]
Value creation comes from within the platform (Cosmonauts World) itself. Providing swag could be one way of incentivizing for early submission. If we ever start doing that, Pavlov's dog would not stop salivating. It will be difficult for us to stop giving out swags once we pick up traction. We shouldn't start from the bottom-up solution. We could just increase the awareness of the platform since there's no other way for the projects to be showcased atm.

If teams pop up out of the blue, we could just direct them here and create a PR to be added to Cosmonauts World. 🚣🏼‍♂️

Fyi I'm planning to add more discovery mechanisms feature, e.g. `recently added` project, built with (`Go`, `JavaScript`), improve DX https://github.com/lovincyrus/cosmonauts-world/issues/57, so devs can get onboarded easily. There is no need to give away swag to add their projects here. 👀

**Comment by haymond** [comment]
> It will be difficult for us to stop giving out swags once we pick up traction.

Possibly. It's also say swag will be give out for one more month and then retire that process. 

>  There is no need to give away swag to add their projects here.

This was a suggestion Peng brought up in another meeting. Perhaps we could pin [Cosmonauts World](https://cosmonauts.world/) on the [Cosmos Forum](https://forum.cosmos.network/) and the [Cosmos Reddit](https://www.reddit.com/r/cosmosnetwork/) so people know to post there, which could help with the discovery mechanisms.

**Comment by lovincyrus** [comment]
> Possibly. We could also say swag will be give out for one more month and then retire that process.

Not a bad idea.

Asmodat has already pinned Cosmonauts World on top of the Cosmos Forum here: https://github.com/lovincyrus/cosmonauts-world/issues/37#issuecomment-567273926

Feel free to post about Cosmonauts World on Cosmos Reddit @haymond 🤳🏼

**Comment by haymond** [comment]
Posted! I'll share feedback when it comes.
